### ISSUE TITLE
ChatTest is Failing

### ISSUE THREAD

**Issue by ngzax** [maccman/holla#13]
For example:

3) Error:
test_the_truth(JuggernautObserverTest):
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'holla2_test.chats' doesn't exist: DELETE FROM `chats`

It doesn't appear that there is anything in the db schema that ever creates this table? What am I missing?

**Comment by maccman** [comment]
There aren't any tests for Holla, so it's quite likely the test schema is broken.

**Comment by ngzax** [comment]
Ah, ok. Yes, you have some old tests in there then that expect a table named "chats."
Are you interested in having some tests?
Would you like me to clean up and send you a patch?

**Comment by maccman** [comment]
Sure, if have a sec that would be great.

**Comment by ngzax** [comment]
Ok.  Will do.

In the meantime, I have a 2 small commits that make it so the database.yml isn't checked in. Most rails projects I have collaborated on use the convention of database.yml.example and ignoring database.yml so that you don't potentially have passwords, plus (as is my case) you want to use a different backend.

Not sure if you have a strong opinion on that.  I can submit a pull request, you can take it or leave it. :)
