### ISSUE TITLE
Can't connect with custom host/port

### ISSUE THREAD

**Issue by seanrucker** [maccman/holla#15]
I installed Juggernaut on Heroku using this Gist: 

https://gist.github.com/1003748

Now I'm trying to test out connecting to it from my local webserver. 

```
var jug = new Juggernaut({
    host: 'mywebapp.herokuapp.com',
    port: 80
});

console.log(jug.options.host); // mywebapp.herokuapp.com
console.log(jug.options.port); // 80

jug.on('connect', function() { 
    console.log('connect');
});

jug.on('disconnect', function() { 
    console.log('disconnect');
});

jug.subscribe('channel1', function(data) {
    console.log("Got data: " + data); 
});
```

This produces an error: 

Invalid url for WebSocket ws://[object Object]:5000/socket.io/websocket

It seems to be using my local port and the host is an object?

**Comment by maccman** [comment]
This ticket should really be on Juggernaut's tracker. Anyway, can you
confirm you're using the latest juggernaut.js file from the github repo.

On Tue, Jul 5, 2011 at 11:24 AM, seanrucker <
reply@reply.github.com>wrote:

> I installed Juggernaut on Heroku using this Gist:
> 
> https://gist.github.com/1003748
> 
> Now I'm trying to test out connecting to it from my local webserver.
> 
>    var jug = new Juggernaut({
>        host: 'mywebapp.herokuapp.com',
>        port: 80
>    });
> 
>    console.log(jug.options.host); // mywebapp.herokuapp.com
>    console.log(jug.options.port); // 80
> 
>    jug.on('connect', function() {
>        console.log('connect');
>    });
> 
>    jug.on('disconnect', function() {
>        console.log('disconnect');
>    });
> 
>    jug.subscribe('channel1', function(data) {
>        console.log("Got data: " + data);
>    });
> 
> This produces an error:
> 
> Invalid url for WebSocket ws://[object Object]:5000/socket.io/websocket
> 
> It seems to be using my local port and the host is an object?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/holla/issues/15

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by seanrucker** [comment]
Oops, didn't realize I was on the holla repo.

I dit a git clone from git://github.com/maccman/juggernaut.git as per the Gist this morning so it should be the latest.

Is it juggernaut.js I'm supposed to be using? I am using application.js.

```
<script type="text/javascript" src="http://mywebapp.herokuapp.com/application.js"></script>
```

**Comment by seanrucker** [comment]
I am seeing this error in the JS console on line 790 of application.js

```
SYNTAX_ERR: DOM Exception 12: An invalid or illegal string was specified.
```

**Comment by ravi8485** [comment]
I am also seeing the same issue, were you able to solve this

**Comment by seanrucker** [comment]
No I wasn't... :(

Hoping maccman will help out. Should we move this to Juggernaut's issue tracker to get some more traction?

**Comment by maccman** [comment]
Yup - that would be great. Thanks.

On Tue, Jul 12, 2011 at 9:42 AM, seanrucker <
reply@reply.github.com>wrote:

> No I wasn't... :(
> 
> Hoping maccman will help out. Should we move this to Juggernaut's issue
> tracker to get some more traction?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/holla/issues/15#issuecomment-1554696

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by seanrucker** [comment]
Moved to Juggernaut's issue tracker.

https://github.com/maccman/juggernaut/issues/87
