### ISSUE TITLE
Juggernaut is down, no feedback

### ISSUE THREAD

**Issue by yebyen** [maccman/holla#17]
I tried deploying this on my Debian GNU/kFreeBSD server only to learn that Node.JS is not supported on that platform.

So I wasn't able to bring up Juggernaut.  But everything else works.  Except.  When you publish messages to a server that does not have Juggernaut, you should get some feedback that your messages are not going out.  I'm thinking something less obtrusive than an alert.  Like turbogears alerts.  Just a visual control that lets you know that there is no web socket backend, without getting in your way, so that when you try to send messages, you don't have the expectation that they're being saved or going anywhere.

KPB

**Comment by maccman** [comment]
This should probably be on the Juggernaut project issues list. I don't think a message is necessary, that's the beauty of pubsub - publishers aren't dependent on subscribers.

**Comment by yebyen** [comment]
OK.  I think from a user interface standpoint, juggernaut is down is a critical message that the user should receive.  Juggernaut does not have the capacity to add a message to the database when it is down, and it will never.

The issue is a Node.JS issue, I'll report to those guys that Node does not compile on Debian GNU/kFreeBSD.

Thanks for quick turnaround.

**Comment by XULRunner42** [comment]
I will further admit that it's a really elegant failure.  I wouldn't want random unauthorized write access to my blog, precisely why this machine is running FreeBSD ^_^
