### ISSUE TITLE
http://getholla.com/ is broken

### ISSUE THREAD

**Issue by cwb** [maccman/holla#2]
The demo site listed in README.markdown is returning:

```
It works!

This is the default web page for this server.

The web server software is running but no content has been added, yet.
```

I couldn't figure out a better place to report that, so please accept my apology if it is totally inappropriate here!

**Comment by maccman** [comment]
Yes, took it down as it was a bit expensive. Can't host it on heroku either as Juggernaut doesn't work on there, looking for someone to volunteer one. I need to update the README to remove the demo site (and fix the images).
