### ISSUE TITLE
welcome the new holla 2 

### ISSUE THREAD

**Issue by lolomarx** [maccman/holla#5]
welcome the new holla 2 !!! we will the first one user. ;-)

**Comment by maccman** [comment]
Cheers, let me know what you think.

**Comment by sebouh** [comment]
Holla 2 looks good is running a lot smoother on the backend.. it seems like with a few javascript tweaks it will run in firefox as well. one thing i can't get to work is loading the roster, and getting more than one client subscribed to a channel. Is that functionality not ready yet?
