### ISSUE TITLE
Any steps to get started?

### ISSUE THREAD

**Issue by crazyarmo1** [maccman/holla#6]
I've run bundle install, rake db:create, and launched the server. When I try to open the app I get "...messages table doesn't exist." thanks.

**Comment by maccman** [comment]
Holla 2 isn't completely finished yet - use the 'original' branch for now.

On Mon, Mar 28, 2011 at 9:33 PM, crazyarmo1 <
reply@reply.github.com>wrote:

> I've run bundle install, rake db:create, and launched the server. When I
> try to open the app I get "...messages table doesn't exist." thanks.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/holla/issues/6

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by maccman** [comment]
Give it a go now
